### ISSUE TITLE
Urls redirects

### ISSUE THREAD

**Issue by nicholasess** [nicholasess/metatags#1]
Create function to verify if url has a redirect and return data from main url.

**Comment by andreabadesso** [comment]
Request library by default follows redirects, can you show an example of a page that won't work?

You can try passing followAllRedirects: true on the first argument (changing uri as well) to follow redirects even if the page does not return status code 3xx

**Comment by nicholasess** [comment]
@andreabadesso I try the website http://uol.com, but not return metatags by http://uol.com.br. It return metatags with field location: http://uol.com.br
